apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-sidecar-config
  namespace: app
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush               1
        Log_Level           info
        Daemon              off
    [INPUT]
        Name                tail
        Path                /log/*.log
        Tag                 service
        Refresh_Interval    10
        Mem_Buf_Limit       50MB   
        Skip_Long_Lines     On      
    [OUTPUT]
        Name                forward
        Match               *
        Host                SVC_IP
        Port                24224
        Retry_Limit         False
