apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wlstmd
  name: wlstmd-nginx2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wlstmd
  template:
    metadata:
      labels:
        app: wlstmd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: key
                    operator: In
                    values:
                      - worker2
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
