apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: hostpath-pod
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: hostpath-volume
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /tmp/webpage
        type: Directory # Directory
