apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: php-apache-cron-scaled
spec:
  minReplicaCount: 0
  maxReplicaCount: 2
  pollingInterval: 30
  cooldownPeriod: 300
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Seoul
        start: 00,15,30,45 * * * *
        end: 05,20,35,50 * * * *
        desiredReplicas: "1"
